### ISSUE TITLE
Doesn't work with the latest vs code

### ISSUE THREAD

**Issue by blueberryapple** [seivan/swipe-to-navigate#3]
Doesn't work with magic trackpad or regular macbook pro trackpad three finger swipe. I've tried setting it to `tabs` and `recent-code`, but three finger swipe does nothing.

## versions
- vs code 1.4.6
- macos 10.15.5
- swipe to navigate extension 1.0.3
- monkey patch extension 0.1.7

**Comment by seivan** [comment]
Sorry it should be better documented. After every update, the extension will notify you that the extension has been disabled because of this [discussion](https://github.com/microsoft/vscode/issues/82588) 

![image](https://user-images.githubusercontent.com/55424/84489766-7a9cd780-aca2-11ea-90cb-d9fc967f6ec8.png)

You can re-enable  it by selecting `re-apply` and preferably do a hard restart, or just press the `restart` button that pops up after, but I prefer the former as it's currently a bit wonky. 



I just tried it with these and it worked: 
```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

If you missed the notification, you can re-enable it via 
![image](https://user-images.githubusercontent.com/55424/84490067-ed0db780-aca2-11ea-9379-24f3840462aa.png)
**Just make sure to restart**  after! I generally just do `cmd+q` after enabling for a hard restart. 


For future fixes I'll make a better system for notify and add a better named command for easier discovery. 
I'll close this for now, but feel free to reopen if it doesn't fix your issue.

**Comment by seivan** [comment]
@blueberryapple Did it work out for you?

**Comment by blueberryapple** [comment]
@seivan I tried re-enabling monkeypatch, but it still didn't work. So I also tried reinstalling the extension and still couldn't get it working. Restarting between each step with `cmd q`. Maybe I'm using it wrong? I'm swiping with three fingers horizontally. I have the same versions as you in the code snippet.

**Comment by seivan** [comment]
@blueberryapple Open up the web inspector ("Toggle Developer Tools" or `alt+cmd+I`) and check if you see `Monkey Patch is active.` & `Registered Swipe Listener!` logged in the console. 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/55424/84602369-2868db80-ae87-11ea-90b4-5c8616e83e2b.png">

**Comment by seivan** [comment]
@blueberryapple How does your config look exactly, paste it in codeblocks here. 

Also how does your trackpad settings look like? 

![README](https://github.com/seivan/swipe-to-navigate/blob/develop/resources/settings.png?raw=true)

**Comment by blueberryapple** [comment]
@seivan that was it! I totally missed the part about changing the `swipe between pages`  🤦‍♂️. After setting that, everything works as expected. Thanks for being patient with me.

**Comment by seivan** [comment]
@blueberryapple It's partially my fault for not mentioning it until you brought this up, glad it worked out.

**Comment by mojtabacazi** [comment]
@seivan For me it swipes backward! On MBP when I swipe right it goes back which is opposite of every other app. Is there a setting for it?

**Comment by seivan** [comment]
@mojtabacazi 

Create a new issue for this, and try to clarify what these means: 
> when I swipe right it goes back

> which is opposite of every other app

It's very unclear.

**Comment by mojtabacazi** [comment]
@seivan Moving 3 fingers from Left to Right on touch bar Should trigger the "back" action, correct? 
For me it triggers the forward action

**Comment by seivan** [comment]
@mojtabacazi Please create a new issue if you want help. 
Also it's still unclear, what would you consider "back" action be, but swiping from the left side of the touch pad to the right means different things depending on your settings which you haven't pasted either.
