### ISSUE TITLE
Maybe the direction is reversed?

### ISSUE THREAD

**Issue by ynrng** [seivan/swipe-to-navigate#6]
Thanks for this.
Some suggestions.

Now if I swipe from right to left, it goes backward. Vice versa.
A little counter-instinctive, maybe change it to behave like Chrome or give an option.

And can I use two fingers instead of three?

**Comment by seivan** [comment]
> Now if I swipe from right to left, it goes backward. Vice versa.
A little counter-instinctive, maybe change it to behave like Chrome or give an option.

Correct me if I am wrong here: 

Are you saying swiping **from** *right* to *left* to traverse back is counter-intuitive? 

Imagine these arrows and you want to move where the arrow is pointing towards.
<img width="73" alt="image" src="https://user-images.githubusercontent.com/55424/99943141-1ca40e00-2d71-11eb-8c30-5ba5c819469c.png">

So if you want to go back to previous, you'd swipe from right to left. 

Though I think I understand where you're coming from, since it's not the same as "scrolling" horizontally on a device with your fingers, but it is the default gestures on macOS.

I could add an option to reverse directions if it's really important to you. 


> And can I use two fingers instead of three?

Depends on your settings I suppose, but I haven't tested nor can I guarantee that it would work, but try changing these settings: 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/55424/99943559-c8e5f480-2d71-11eb-9ea7-8be1fb5cbbec.png">

**Comment by seivan** [comment]
@sugaE I am closing this, feel free to reopen if it's not satisfactory.

**Comment by ynrng** [comment]
Hi seivan.
Thanks for reply.

> Are you saying swiping from right to left to traverse back is counter-intuitive?

For me, yes. Maybe it's because some daily-use applications have this reversed direction. Like Chome or Xcode.
So in Chome or Xcode, if I want to go back in history, I swipe from left to right. It is really hard to change the habit.
(I think this kind of direction is more consistent with portable devicedevice, or like reading a physical book. When you want to go back, you swipe right.)

> Depends on your settings I suppose, but I haven't tested nor can I guarantee that it would work, but try changing these settings

Tried. Didn't work. If I set other gestures, like 2 fingers, this plugin won't work.

Anyhow, great work. Thanks for your contribution.

**Comment by seivan** [comment]
I can’t help with the number of fingers, the event is coming from Apple, but I’ll investigate for alternatives. 

That being said, regarding the direction I can  allow you to reverse it as option, is that good enough? I understand issues with muscle memory all to well so I’m willing to add that option if you will test it for me?

**Comment by ynrng** [comment]
It seems that this plugin somehow did not work on my current computer. Had no idea why.
(Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (2 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0)

I will let you know when it starts to work again and am happy to test then. 

And as I was trying to fix the issue myself, I found out some history with this plugin.
For future reference:
https://github.com/microsoft/vscode/pull/23663
https://github.com/microsoft/vscode/pull/82528


Thx.

**Comment by seivan** [comment]
> It seems that this plugin somehow did not work on my current computer. Had no idea why.
> (Version: 1.56.2
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-12T17:44:30.902Z (2 wks ago)
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Darwin x64 20.4.0)

It's because you updated VSCode and didn't re-enable it. 

> I will let you know when it starts to work again and am happy to test then.
> 
> And as I was trying to fix the issue myself, I found out some history with this plugin.
> For future reference:
> [microsoft/vscode#23663](https://github.com/microsoft/vscode/pull/23663)
> [microsoft/vscode#82528](https://github.com/microsoft/vscode/pull/82528)

Yeah I am the author of the original implementation, but the VSCode team doesn't want to rely on Electron since they want this to work in a browser as well - until browsers get native support for touchpad gestures, we have to rely on a monkey patch. 

This requires you to "re-enable" it on each update and restart VSCode. It's annoying but so far the only way. 

The implementation basically hijacks the bootstrap sequence of VSCode and overloads functions to add additional functionality like the swipe gestures. I haven't seen a way to do that with the default extension API, if you have suggestions I am more than happy to change it.

**Comment by seivan** [comment]
Edit: I originally accidentally edited your [comment](https://github.com/seivan/swipe-to-navigate/issues/6#issuecomment-851620084) instead of quote reply - sorry about that, I had it reversed! 

> For me, yes. Maybe it's because some daily-use applications have this reversed direction. Like Chome or Xcode.
So in Chome or Xcode, if I want to go back in history, I swipe from left to right. It is really hard to change the habit.
(I think this kind of direction is more consistent with portable device, or like reading a physical book. When you want to go back, you swipe right.)

Hmm.. not sure if it has changed in Big Sur, but in Catalina and previous major versions this is the default swipe direction, I myself come from Xcode development and I wanted this in VSCode, could it be that you have reversed it somehow? 

On a default macOS for Safari, Chrome and Xcode, swiping **from** `right` **to** `left` will go to "previous" code-snippet/tab/selection/page. 
Which is the default for this extension, are you saying that you're getting different results here?

**Comment by seivan** [comment]
@robsontenorio Are you ok with the changes in https://github.com/seivan/swipe-to-navigate/pull/11 ?

**Comment by ynrng** [comment]
> On a default macOS for Safari, Chrome and Xcode, swiping **from** `right` **to** `left` will go to "previous" code-snippet/tab/selection/page.
> Which is the default for this extension, are you saying that you're getting different results here?


I wonder if it's because we didn't use the same number of fingers.
If the system setting is set to "2" fingers to swipe between pages, then swipe right is previous.
If the system setting is set to "3", then like you said, it's the same direction as the pointer direction.
Puzzle solved.

**Comment by seivan** [comment]
> > On a default macOS for Safari, Chrome and Xcode, swiping **from** `right` **to** `left` will go to "previous" code-snippet/tab/selection/page.
> > Which is the default for this extension, are you saying that you're getting different results here?
> 
> I wonder if it's because we didn't use the same number of fingers.
> If the system setting is set to "2" fingers to swipe between pages, then swipe right is previous.
> If the system setting is set to "3", then like you said, it's the same direction as the pointer direction.
> Puzzle solved.

There you go, so it does support 2 fingers then? 
But doesn't that conflict with horizontal scroll somehow? What happens if your code is wrapping long enough to scroll sideways? 

@robsontenorio you want to read this.

**Comment by ynrng** [comment]
> There you go, so it does support 2 fingers then?
> But doesn't that conflict with horizontal scroll somehow? What happens if your code is wrapping long enough to scroll sideways?

In other apps, it works. And no conflicts as the navigation behaviour is only triggered when scroll bar reaches the very left or right boundary. 
BUT in Xcode, it won't work. Need to set the system setting to 3 fingers.

**Comment by robsontenorio** [comment]
The horizontal scroll is different from 2 fingers swipe gesture. 

try safari with resized window and you will can scroll horizontally  without conflicting with swipe page feature. 

But if electron can’t handle it , so no deal :)

**Comment by ynrng** [comment]
I didn't find any code that defines what a "swipe" event is. So hard to say if it's sync with the system preference.

Theoretically, it is possible to use 2-fingers config if we can listen to the scroll event.
But it will require quite some design to decide when to enable the navigation and not mess up with the original h-scroll behaviour. Especially if smooth action is desired.
I currently don't have the energy. 
For future reference: https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/base/common/scrollable.ts

**Comment by seivan** [comment]
Closing in favour https://github.com/seivan/swipe-to-navigate/issues/18
I'll be adding the detailed navigation actions that vscode offers in the documentation so it's obvious what settings you've picked.
